import type { ProgressBarItem } from "@interfaces/Ievent";

export const FullMoonEventItems: ProgressBarItem[] = [
  {
    page: 1,
    progress: 1250,
    amount: 10,
    name: "Amphora Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 2500,
    amount: 2500,
    name: "Shining Silver Essences",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 3750,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 5000,
    amount: 1,
    name: "Big Varholm Survival Chest",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 6250,
    amount: 5,
    name: "Vial of Werewolf Blood",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 8750,
    amount: 3000,
    name: "Shining Silver Essences",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 10000,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 11250,
    amount: 12,
    name: "Amphora Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 12500,
    amount: 7,
    name: "Vial of Werewolf Blood",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 13750,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 1,
    progress: 15000,
    amount: 1,
    name: "Gem of Enhancement",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 1250,
    amount: 5,
    name: "Kitchen Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 2500,
    amount: 10,
    name: "Community Coin",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 3750,
    amount: 2000,
    name: "Shining Silver Essences",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 5000,
    amount: 2,
    name: "Five-Hole Bone Flute",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 6250,
    amount: 1,
    name: "Big Varholm Survival Chest",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 8750,
    amount: 3,
    name: "Amphora Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 10000,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 11250,
    amount: 3,
    name: "Amphora Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 12500,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 13750,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 2,
    progress: 15000,
    amount: 10,
    name: "Kitchen Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 1250,
    amount: 5,
    name: "Amphora Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 2500,
    amount: 5,
    name: "Five-Hole Bone Flute",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 3750,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 5000,
    amount: 10,
    name: "Community Coin",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 6250,
    amount: 10,
    name: "	Kitchen Coin",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 8750,
    amount: 10,
    name: "Broken Multitool",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 10000,
    amount: 5,
    name: "Amphora Key",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 11250,
    amount: 10,
    name: "Dragon Bones",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 12500,
    amount: 5,
    name: "Five-Hole Bone Flute",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 13750,
    amount: 3000,
    name: "Shining Silver Essences",
    icon: "/images/events/new-moon/attire.png",
  },
  {
    page: 3,
    progress: 15000,
    amount: 1,
    name: "Jewel Chest",
    icon: "/images/events/new-moon/attire.png",
  },
];
