import type { ProgressBarItem } from "@interfaces/Ievent";
import { ImageExporter } from "@utils/ImageExporter";

export const FullMoonDraken1 = 2500;

export const FullMoonDraken2 = 7000;

export const fullMoonTips: string[] = [];

export const FullMoonEventItems1: ProgressBarItem[] = [
  {
    page: 1,
    progress: 625,
    amount: 3,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 1250,
    amount: 1000,
    name: "Shining Silver Essences",
    icon: ImageExporter.shinySilverEssence,
  },
  {
    page: 1,
    progress: 1875,
    amount: 2,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 1,
    progress: 2500,
    amount: 50,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 1,
    progress: 3125,
    amount: 1,
    name: "Big Varholm Survival Chest",
    icon: ImageExporter.varholmSurvivalChest,
  },
  {
    page: 1,
    progress: 3700,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 1,
    progress: 4325,
    amount: 75,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 1,
    progress: 5000,
    amount: 1,
    name: "Fullmoon Reward Chest",
    icon: ImageExporter.varholmSurvivalChest,
  },
  {
    page: 1,
    progress: 5575,
    amount: 1500,
    name: "Shining Silver Essences",
    icon: ImageExporter.shinySilverEssence,
  },
  {
    page: 1,
    progress: 6200,
    amount: 7,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 6825,
    amount: 5,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 1,
    progress: 7450,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: ImageExporter.shinyFullmoonChest,
  },
];

export const FullMoonEventItems2: ProgressBarItem[] = [
  {
    page: 1,
    progress: 1250,
    amount: 10,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 2500,
    amount: 2500,
    name: "Shining Silver Essences",
    icon: ImageExporter.shinySilverEssence,
  },
  {
    page: 1,
    progress: 3750,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 1,
    progress: 5000,
    amount: 1,
    name: "Big Varholm Survival Chest",
    icon: ImageExporter.varholmSurvivalChest,
  },
  {
    page: 1,
    progress: 6250,
    amount: 5,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 1,
    progress: 8750,
    amount: 3000,
    name: "Shining Silver Essences",
    icon: ImageExporter.shinySilverEssence,
  },
  {
    page: 1,
    progress: 10000,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: ImageExporter.shinyFullmoonChest,
  },
  {
    page: 1,
    progress: 11250,
    amount: 12,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 12500,
    amount: 7,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 1,
    progress: 13750,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: ImageExporter.shinyFullmoonChest,
  },
  {
    page: 1,
    progress: 15000,
    amount: 1,
    name: "Gem of Enhancement",
    icon: ImageExporter.gemJoker,
  },
  {
    page: 2,
    progress: 1250,
    amount: 5,
    name: "Kitchen Key",
    icon: ImageExporter.kitchenKey,
  },
  {
    page: 2,
    progress: 2500,
    amount: 10,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 3750,
    amount: 2000,
    name: "Shining Silver Essences",
    icon: ImageExporter.shinySilverEssence,
  },
  {
    page: 2,
    progress: 5000,
    amount: 2,
    name: "Five-Hole Bone Flute",
    icon: ImageExporter.fiveHoleBoneFlute,
  },
  {
    page: 2,
    progress: 6250,
    amount: 1,
    name: "Big Varholm Survival Chest",
    icon: ImageExporter.varholmSurvivalChest,
  },
  {
    page: 2,
    progress: 8750,
    amount: 3,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 2,
    progress: 10000,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 2,
    progress: 11250,
    amount: 3,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 2,
    progress: 12500,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 2,
    progress: 13750,
    amount: 1,
    name: "Shining Fullmoon Reward Chest",
    icon: ImageExporter.shinyFullmoonChest,
  },
  {
    page: 2,
    progress: 15000,
    amount: 10,
    name: "Kitchen Key",
    icon: ImageExporter.kitchenKey,
  },
  {
    page: 3,
    progress: 1250,
    amount: 5,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 3,
    progress: 2500,
    amount: 5,
    name: "Five-Hole Bone Flute",
    icon: ImageExporter.fiveHoleBoneFlute,
  },
  {
    page: 3,
    progress: 3750,
    amount: 3,
    name: "Vial of Werewolf Blood",
    icon: ImageExporter.fullmoonVial,
  },
  {
    page: 3,
    progress: 5000,
    amount: 10,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 3,
    progress: 6250,
    amount: 10,
    name: "Kitchen Coin",
    icon: ImageExporter.kitchenKey,
  },
  {
    page: 3,
    progress: 8750,
    amount: 10,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 10000,
    amount: 5,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 3,
    progress: 11250,
    amount: 10,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 3,
    progress: 12500,
    amount: 5,
    name: "Five-Hole Bone Flute",
    icon: ImageExporter.fiveHoleBoneFlute,
  },
  {
    page: 3,
    progress: 13750,
    amount: 3000,
    name: "Shining Silver Essences",
    icon: ImageExporter.shinySilverEssence,
  },
  {
    page: 3,
    progress: 15000,
    amount: 1,
    name: "Jewel Chest",
    icon: ImageExporter.jewelChest,
  },
];
