import { ImageExporter } from "@utils/ImageExporter";
import type { ProgressBarItem } from "@interfaces/Ievent";

export const GhostFestivalDraken = 2060;
export const GhostFestivalMiniDraken = 2080;

export const GhostFestivalTips: string[] = [
  "Use the 3 hours Ghost Festival Attire to progress as much as possible in a short time. Highly recommended to use the 10% buff as well during this period. Use Realm Path to the Creepy Castle while having the attire on.",
  "To collect pumpkin and spellbound raspberries, you need to interact with the plants in Oldfiend (requires 1 multitool).",
  "You should find a group with 5 people and split in Oldfiend map to farm Sophia's Remedy faster.",
];
export const GhostFestivalMiniTips: string[] = [
  "All 3 Salamander Blaze Buffs cost 50 ghost fire. If you care just for progress bar, use the one that last for 30 minutes. If you want to farm items, use the one that last for 5 minutes.",
  "Highly recommended to get the Jewel of the Frozen Heart",
  "The Soul Seltzer which is required in 3/3 the new quest of Heart and Soul is in the end of 3rd progress bar of mini event.",
];

export const GhostFestivalEventItems: ProgressBarItem[] = [
  {
    page: 1,
    progress: 50,
    amount: 8,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 150,
    amount: 1,
    name: "Sacred Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 250,
    amount: 20,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 1,
    progress: 450,
    amount: 1,
    name: "Ghost Festival Attire (3 Hours)",
    icon: ImageExporter.ghostFestivalAttireTemp,
  },
  {
    page: 1,
    progress: 700,
    amount: 15,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 1000,
    amount: 3,
    name: "Royal Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 1350,
    amount: 1,
    name: "Sophia's Remedy",
    icon: ImageExporter.sophiasRemedy,
  },
  {
    page: 1,
    progress: 1725,
    amount: 50,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 1,
    progress: 2125,
    amount: 1,
    name: "Basic Alchemy Circle (Purple)",
    icon: ImageExporter.basicAlchemyCirclePurple,
  },
  {
    page: 2,
    progress: 150,
    amount: 15,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 2,
    progress: 750,
    amount: 50,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 2,
    progress: 1850,
    amount: 1,
    name: "Pumpkin Candy",
    icon: ImageExporter.pumpkinCandy,
  },
  {
    page: 2,
    progress: 3450,
    amount: 2,
    name: "Pumpkin Candy",
    icon: ImageExporter.pumpkinCandy,
  },
  {
    page: 2,
    progress: 5550,
    amount: 1,
    name: "Ruined Amphora",
    icon: ImageExporter.ruinedAmphora,
  },
  {
    page: 2,
    progress: 8400,
    amount: 3,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 2,
    progress: 13000,
    amount: 1,
    name: "Spellbound Raspberries",
    icon: ImageExporter.spellboundRaspberries,
  },
  {
    page: 3,
    progress: 1250,
    amount: 1999,
    name: "Light Essence",
    icon: ImageExporter.magicLightEssence,
  },
  {
    page: 3,
    progress: 2975,
    amount: 2,
    name: "Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 5475,
    amount: 100,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 3,
    progress: 8600,
    amount: 50,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 3,
    progress: 12350,
    amount: 100,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 16725,
    amount: 2,
    name: "Dragon Blood Box",
    icon: ImageExporter.dragonBloodBox,
  },
  {
    page: 3,
    progress: 21725,
    amount: 1,
    name: "Jewel of Ghost Power",
    icon: ImageExporter.jewelGhostPower,
  },
  {
    page: 3,
    progress: 28600,
    amount: 10,
    name: "Halloween Gift Voucher",
    icon: ImageExporter.halloweenGiftVoucher,
  },
  {
    page: 4,
    progress: 1700,
    amount: 1,
    name: "Refined Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 3700,
    amount: 1999,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 4,
    progress: 6525,
    amount: 50,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 4,
    progress: 10325,
    amount: 2,
    name: "Brilliant Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 15625,
    amount: 250,
    name: "Anxiety Shard",
    icon: ImageExporter.epicAnxietyShard,
  },
  {
    page: 4,
    progress: 21925,
    amount: 2,
    name: "Brilliant Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 28925,
    amount: 2,
    name: "Dragon Bone Elixir",
    icon: ImageExporter.dragonBoneElixir,
  },
  {
    page: 4,
    progress: 37275,
    amount: 50,
    name: "Perforated Dragon Tooth",
    icon: ImageExporter.perforatedDragonTooth,
  },
  {
    page: 4,
    progress: 46575,
    amount: 1,
    name: "Exquisite Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 57875,
    amount: 100,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 4,
    progress: 70775,
    amount: 50,
    name: "Perforated Dragon Tooth",
    icon: ImageExporter.perforatedDragonTooth,
  },
  {
    page: 4,
    progress: 86075,
    amount: 1,
    name: "Imperial Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 103375,
    amount: 1,
    name: " Jewel of Ghost Power",
    icon: ImageExporter.jewelGhostPower,
  },
  {
    page: 4,
    progress: 123775,
    amount: 1,
    name: "Eerie Jack-O'-Lantern Helmet",
    icon: ImageExporter.eerieJackOLanternHelmet,
  },
];

export const GhostFestivalMiniEventItems: ProgressBarItem[] = [
  {
    page: 1,
    progress: 200,
    amount: 3000,
    name: "Light Essence",
    icon: ImageExporter.magicLightEssence,
  },
  {
    page: 1,
    progress: 800,
    amount: 2,
    name: "Sophia's Remedy",
    icon: ImageExporter.sophiasRemedy,
  },
  {
    page: 1,
    progress: 1800,
    amount: 3,
    name: "Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 3200,
    amount: 50,
    name: "Ghost Fire",
    icon: ImageExporter.ghostFire,
  },
  {
    page: 1,
    progress: 5000,
    amount: 1,
    name: "Jalapeño Cookie",
    icon: ImageExporter.jalapenoCookie,
  },
  {
    page: 1,
    progress: 7200,
    amount: 50,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 1,
    progress: 9800,
    amount: 1,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 1,
    progress: 12550,
    amount: 1,
    name: "Ghost Festival Attire (3 Hours)",
    icon: ImageExporter.ghostFestivalAttireTemp,
  },
  {
    page: 1,
    progress: 15500,
    amount: 1,
    name: "Spellbound Raspberries",
    icon: ImageExporter.spellboundRaspberries,
  },
  {
    page: 2,
    progress: 1000,
    amount: 2,
    name: "Refined Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 2,
    progress: 4000,
    amount: 100,
    name: "Life Force",
    icon: ImageExporter.lifeForce,
  },
  {
    page: 2,
    progress: 9000,
    amount: 30,
    name: "Perforated Dragon Tooth",
    icon: ImageExporter.perforatedDragonTooth,
  },
  {
    page: 2,
    progress: 14000,
    amount: 50,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 2,
    progress: 21000,
    amount: 2,
    name: "Dragon Bone Elixir",
    icon: ImageExporter.dragonBoneElixir,
  },
  {
    page: 2,
    progress: 30000,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 39000,
    amount: 3,
    name: "Sophia's Remedy",
    icon: ImageExporter.sophiasRemedy,
  },
  {
    page: 2,
    progress: 50000,
    amount: 1,
    name: "Ruined Amphora",
    icon: ImageExporter.ruinedAmphora,
  },
  {
    page: 3,
    progress: 1000,
    amount: 100,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 3,
    progress: 3000,
    amount: 2,
    name: "Brilliant Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 6000,
    amount: 50,
    name: "Perforated Dragon Tooth",
    icon: ImageExporter.perforatedDragonTooth,
  },
  {
    page: 3,
    progress: 10000,
    amount: 1,
    name: "Golden Goose",
    icon: ImageExporter.goldenGoose,
  },
  {
    page: 3,
    progress: 15000,
    amount: 100,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 3,
    progress: 21500,
    amount: 1,
    name: "Jewel of the Frozen Heart",
    icon: ImageExporter.jewelFrozenHeart,
  },
  {
    page: 3,
    progress: 29500,
    amount: 100,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 3,
    progress: 39000,
    amount: 1,
    name: "Exquisite Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 50000,
    amount: 150,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 62500,
    amount: 7,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 3,
    progress: 76500,
    amount: 1,
    name: "Rune of Enhancement",
    icon: ImageExporter.runeJoker,
  },
  {
    page: 3,
    progress: 92000,
    amount: 1,
    name: "Imperial Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 109000,
    amount: 1,
    name: "Jewel Chest",
    icon: ImageExporter.jewelChest,
  },
  {
    page: 3,
    progress: 127500,
    amount: 10,
    name: "Halloween Gift Voucher",
    icon: ImageExporter.halloweenGiftVoucher,
  },
  {
    page: 3,
    progress: 147500,
    amount: 1,
    name: "Carnival Pace",
    icon: ImageExporter.carnivalPace,
  },
  {
    page: 3,
    progress: 169000,
    amount: 1,
    name: "Soul Seltzer",
    icon: ImageExporter.soulSeltzer,
  },
];
