import type { ProgressBarItem } from "@interfaces/Ievent";
import { ImageExporter } from "@utils/ImageExporter";

export const SargonDraken1 = 750;
export const SargonDraken2 = 1000;
export const SargonDraken3 = 1500;
export const SargonDraken4 = 2000;
export const SargonDraken5 = 2500;

export const SargonTips: string[] = [
  "The attire is not worth to purchase, as it does not provide a significant boost.",
  "This event is best farmed with at least 2 players, as the first map is quite long to solo.",
  "Each player should try to get at least 1 book drop per run to maximize clear speed.",
  "Consider using a speedrun strategy to clear the first map quickly.",
  "You can do bloodchests in the first map, but it is not very efficient.",
  "If you are struggling to find a group, consider joining the official DSO Discord and looking for a party there.",
];

export const SargonEventItems1: ProgressBarItem[] = [
  {
    page: 1,
    progress: 166,
    amount: 15,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 1,
    progress: 332,
    amount: 10,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 498,
    amount: 50,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 1,
    progress: 665,
    amount: 1,
    name: "Sacred Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 832,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 1,
    progress: 1000,
    amount: 1000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 1,
    progress: 1166,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 1,
    progress: 1322,
    amount: 15,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 1,
    progress: 1500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 2,
    progress: 300,
    amount: 30,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 2,
    progress: 600,
    amount: 100,
    name: "Gilded Clover",
    icon: ImageExporter.clover,
  },
  {
    page: 2,
    progress: 900,
    amount: 75,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 2,
    progress: 1200,
    amount: 25,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 2,
    progress: 1500,
    amount: 35,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 2,
    progress: 1800,
    amount: 1,
    name: "Royal Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 2,
    progress: 2100,
    amount: 1500,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 2,
    progress: 2400,
    amount: 40,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 2700,
    amount: 1,
    name: "Shadow Portal",
    icon: ImageExporter.sargonPortal,
  },
  {
    page: 2,
    progress: 3000,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonEquipment,
  },
];

export const SargonEventItems2: ProgressBarItem[] = [
  {
    page: 1,
    progress: 312,
    amount: 10,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 1,
    progress: 624,
    amount: 1,
    name: "Sacred Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 936,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 1,
    progress: 1248,
    amount: 5,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 1,
    progress: 1560,
    amount: 2000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 1,
    progress: 1872,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 1,
    progress: 2184,
    amount: 15,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 1,
    progress: 2500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 2,
    progress: 611,
    amount: 15,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 2,
    progress: 1222,
    amount: 25,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 2,
    progress: 1833,
    amount: 35,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 2,
    progress: 2444,
    amount: 1,
    name: "Royal Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 2,
    progress: 3055,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 2,
    progress: 3666,
    amount: 1000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 2,
    progress: 4277,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 4888,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 2,
    progress: 5500,
    amount: 30,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 3,
    progress: 700,
    amount: 30,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 3,
    progress: 1400,
    amount: 100,
    name: "Gilded Clover",
    icon: ImageExporter.clover,
  },
  {
    page: 3,
    progress: 2100,
    amount: 75,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 3,
    progress: 2800,
    amount: 35,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 3,
    progress: 3500,
    amount: 50,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 4200,
    amount: 2,
    name: "Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 4900,
    amount: 1500,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 3,
    progress: 5600,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 3,
    progress: 6400,
    amount: 1,
    name: "Shadow Portal",
    icon: ImageExporter.sargonPortal,
  },
  {
    page: 3,
    progress: 7000,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonEquipment,
  },
];

export const SargonEventItems3: ProgressBarItem[] = [
  {
    page: 1,
    progress: 500,
    amount: 15,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 1,
    progress: 1000,
    amount: 5,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 1500,
    amount: 5,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 1,
    progress: 2000,
    amount: 500,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 1,
    progress: 2500,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 1,
    progress: 3000,
    amount: 1,
    name: "Sacred Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 3500,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 2,
    progress: 687,
    amount: 20,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 2,
    progress: 1374,
    amount: 1,
    name: "Royal Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 2,
    progress: 2061,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 2,
    progress: 2748,
    amount: 3,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 2,
    progress: 4122,
    amount: 1000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 2,
    progress: 4809,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 2,
    progress: 4809,
    amount: 10,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 5500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 3,
    progress: 833,
    amount: 20,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 3,
    progress: 1666,
    amount: 20,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 3,
    progress: 2499,
    amount: 35,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 3332,
    amount: 1,
    name: "Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 4165,
    amount: 25,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 3,
    progress: 4998,
    amount: 1500,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 3,
    progress: 5831,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 3,
    progress: 6664,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 3,
    progress: 7500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 4,
    progress: 772,
    amount: 50,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 4,
    progress: 1544,
    amount: 150,
    name: "Gilded Clover",
    icon: ImageExporter.clover,
  },
  {
    page: 4,
    progress: 2316,
    amount: 100,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 4,
    progress: 3088,
    amount: 30,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 4,
    progress: 3860,
    amount: 50,
    name: "Altered Crescerite",
    icon: ImageExporter.stickerbookUpgrade,
  },
  {
    page: 4,
    progress: 4632,
    amount: 2,
    name: "Refined Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 5404,
    amount: 2000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 4,
    progress: 6176,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 4,
    progress: 6948,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 4,
    progress: 7720,
    amount: 1,
    name: "Shadow Portal",
    icon: ImageExporter.sargonPortal,
  },
  {
    page: 4,
    progress: 8500,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonEquipment,
  },
];

export const SargonEventItems4: ProgressBarItem[] = [
  {
    page: 1,
    progress: 437,
    amount: 15,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 1,
    progress: 874,
    amount: 1,
    name: "Royal Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 1311,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 1,
    progress: 1748,
    amount: 3,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 1,
    progress: 2185,
    amount: 1000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 1,
    progress: 2622,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 1,
    progress: 3059,
    amount: 10,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 1,
    progress: 3500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 2,
    progress: 611,
    amount: 20,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 2,
    progress: 1222,
    amount: 20,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 2,
    progress: 1833,
    amount: 35,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 2,
    progress: 2444,
    amount: 1,
    name: "Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 2,
    progress: 3055,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 2,
    progress: 3666,
    amount: 2000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 2,
    progress: 4277,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 4888,
    amount: 10,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 2,
    progress: 5500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 3,
    progress: 750,
    amount: 20,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 3,
    progress: 1500,
    amount: 75,
    name: "Gilded Clover",
    icon: ImageExporter.clover,
  },
  {
    page: 3,
    progress: 2250,
    amount: 50,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 3,
    progress: 3000,
    amount: 20,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 3,
    progress: 3750,
    amount: 50,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 4500,
    amount: 1,
    name: "Refined Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 5250,
    amount: 3000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 3,
    progress: 6000,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 3,
    progress: 6750,
    amount: 10,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 3,
    progress: 7500,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonEquipment,
  },
  {
    page: 4,
    progress: 681,
    amount: 25,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 4,
    progress: 1362,
    amount: 15,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 4,
    progress: 2043,
    amount: 7,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 4,
    progress: 2724,
    amount: 35,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 4,
    progress: 3405,
    amount: 1,
    name: "Shadow Portal",
    icon: ImageExporter.sargonPortal,
  },
  {
    page: 4,
    progress: 4086,
    amount: 75,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 4,
    progress: 4767,
    amount: 1,
    name: "Imperial Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 5448,
    amount: 3000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 4,
    progress: 6129,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 4,
    progress: 7010,
    amount: 10,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 4,
    progress: 8350,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonEquipment,
  },
  {
    page: 5,
    progress: 83,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 916,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 1749,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 2582,
    amount: 1,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 3415,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 4248,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 5081,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 5914,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 6747,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 7580,
    amount: 3,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 8413,
    amount: 3,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 5,
    progress: 10000,
    amount: 15,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
];

export const SargonEventItems5: ProgressBarItem[] = [
  {
    page: 1,
    progress: 500,
    amount: 10,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 1,
    progress: 1000,
    amount: 5,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 1,
    progress: 1500,
    amount: 5,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 1,
    progress: 2000,
    amount: 1000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 1,
    progress: 2500,
    amount: 10,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 1,
    progress: 3000,
    amount: 2,
    name: "Sacred Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 1,
    progress: 3500,
    amount: 15,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 2,
    progress: 687,
    amount: 20,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 2,
    progress: 1374,
    amount: 2,
    name: "Royal Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 2,
    progress: 2061,
    amount: 10,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 2,
    progress: 2748,
    amount: 5,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 2,
    progress: 3435,
    amount: 2000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 2,
    progress: 4122,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 2,
    progress: 4809,
    amount: 15,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 2,
    progress: 5500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 3,
    progress: 833,
    amount: 25,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 3,
    progress: 1666,
    amount: 20,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 3,
    progress: 2499,
    amount: 50,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 3,
    progress: 3332,
    amount: 2,
    name: "Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 3,
    progress: 4165,
    amount: 15,
    name: "Spirit Stone",
    icon: ImageExporter.reviveStone,
  },
  {
    page: 3,
    progress: 4998,
    amount: 3000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 3,
    progress: 5831,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 3,
    progress: 6664,
    amount: 15,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 3,
    progress: 7500,
    amount: 1,
    name: "Shadow Minion Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 4,
    progress: 850,
    amount: 30,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 4,
    progress: 1700,
    amount: 100,
    name: "Gilded Clover",
    icon: ImageExporter.clover,
  },
  {
    page: 4,
    progress: 2550,
    amount: 50,
    name: "Realm Fragment",
    icon: ImageExporter.realmFragment,
  },
  {
    page: 4,
    progress: 3400,
    amount: 30,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 4,
    progress: 4250,
    amount: 70,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 4,
    progress: 5100,
    amount: 2,
    name: "Refined Trapezoid Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 4,
    progress: 5950,
    amount: 4000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 4,
    progress: 6800,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 4,
    progress: 7650,
    amount: 15,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 4,
    progress: 8500,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 5,
    progress: 909,
    amount: 35,
    name: "Lockpick",
    icon: ImageExporter.lockpick,
  },
  {
    page: 5,
    progress: 1818,
    amount: 25,
    name: "Amphora Key",
    icon: ImageExporter.amphoraKey,
  },
  {
    page: 5,
    progress: 2727,
    amount: 10,
    name: "Mighty Spirit Guard",
    icon: ImageExporter.soulGuardian,
  },
  {
    page: 5,
    progress: 3636,
    amount: 50,
    name: "Fragment of Infernal Passage",
    icon: ImageExporter.infernalPassage,
  },
  {
    page: 5,
    progress: 4545,
    amount: 1,
    name: "Shadow Portal",
    icon: ImageExporter.sargonPortal,
  },
  {
    page: 5,
    progress: 5454,
    amount: 100,
    name: "Broken Multitool",
    icon: ImageExporter.brokenMultitool,
  },
  {
    page: 5,
    progress: 6363,
    amount: 2,
    name: "Imperial Gem Bag",
    icon: ImageExporter.gemBox,
  },
  {
    page: 5,
    progress: 7272,
    amount: 5000,
    name: "Light Essence",
    icon: ImageExporter.epicLightEssence,
  },
  {
    page: 5,
    progress: 8181,
    amount: 20,
    name: "Community Coin",
    icon: ImageExporter.communityCoin,
  },
  {
    page: 5,
    progress: 9090,
    amount: 15,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
  {
    page: 5,
    progress: 10000,
    amount: 1,
    name: "Sargon's Immortal Chest",
    icon: ImageExporter.sargonCostume,
  },
  {
    page: 6,
    progress: 1250,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 2500,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 3750,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 5000,
    amount: 2,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 6250,
    amount: 3,
    name: "mortis_key",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 7500,
    amount: 3,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 8750,
    amount: 3,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 10000,
    amount: 3,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 11250,
    amount: 3,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 12500,
    amount: 4,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 13750,
    amount: 5,
    name: "Mark of Mortis",
    icon: ImageExporter.mortisKey,
  },
  {
    page: 6,
    progress: 15000,
    amount: 25,
    name: "Dragon Bones",
    icon: ImageExporter.dragonBones,
  },
];
