import { Macro } from "../interfaces/Imacro.js";

export const defaultMacros: Macro[] = [
  {
    id: "health-potion",
    name: "Use Health Potion",
    description: "Quickly use a health potion (default key: H)",
    enabled: true,
    onRepeat: false,
    repeat: 1,
    type: "default",
    keybinding: "F5",
    actions: [
      {
        id: "hp-1",
        type: "keyboard-action",
        action: "key-press",
        value: "H",
        wait: 100,
      },
    ],
  },
  {
    id: "mana-potion",
    name: "Use Mana Potion",
    description: "Quickly use a mana potion (default key: M)",
    enabled: true,
    onRepeat: false,
    repeat: 1,
    type: "default",
    keybinding: "F6",
    actions: [
      {
        id: "mp-1",
        type: "keyboard-action",
        action: "key-press",
        value: "M",
        wait: 100,
      },
    ],
  },
  {
    id: "basic-attack-combo",
    name: "Basic Attack Combo",
    description: "Performs a basic attack sequence (Q -> W -> E)",
    enabled: true,
    onRepeat: false,
    repeat: 1,
    type: "default",
    keybinding: "F7",
    actions: [
      {
        id: "combo-1",
        type: "keyboard-action",
        action: "key-press",
        value: "Q",
        wait: 200,
      },
      {
        id: "combo-2",
        type: "keyboard-action",
        action: "key-press",
        value: "W",
        wait: 200,
      },
      {
        id: "combo-3",
        type: "keyboard-action",
        action: "key-press",
        value: "E",
        wait: 100,
      },
    ],
  },
  {
    id: "inventory-toggle",
    name: "Toggle Inventory",
    description: "Open/close inventory window (default key: I)",
    enabled: true,
    onRepeat: false,
    repeat: 1,
    type: "default",
    keybinding: "F8",
    actions: [
      {
        id: "inv-1",
        type: "keyboard-action",
        action: "key-press",
        value: "I",
        wait: 100,
      },
    ],
  },
  {
    id: "skill-rotation",
    name: "Skill Rotation",
    description: "Advanced skill rotation (1->2->3->4)",
    enabled: true,
    onRepeat: false,
    repeat: 1,
    type: "default",
    keybinding: "F9",
    actions: [
      {
        id: "skill-1",
        type: "keyboard-action",
        action: "key-press",
        value: "1",
        wait: 150,
      },
      {
        id: "skill-2",
        type: "keyboard-action",
        action: "key-press",
        value: "2",
        wait: 150,
      },
      {
        id: "skill-3",
        type: "keyboard-action",
        action: "key-press",
        value: "3",
        wait: 150,
      },
      {
        id: "skill-4",
        type: "keyboard-action",
        action: "key-press",
        value: "4",
        wait: 100,
      },
    ],
  },
  {
    id: "sell-inventory",
    name: "Sell Inventory",
    description: "Automates selling items in inventory by right-clicking each slot, skipping locked slots",
    enabled: true,
    onRepeat: false,
    repeat: 1,
    type: "default",
    keybinding: "Ctrl+Alt+F",
    actions: [],
  },
];
